name: simple_timer
description: A Simple Timer Widget that displays the timer progress with various customizable options.
version: 2.0.0
homepage: https://github.com/smladeoye/flutter-simple-timer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
